### PR TITLE
Add support for JAXB 4.0

### PR DESCRIPTION
**Pull request by phax**
Hi guys,
for some Java 11 compatibility project I took the liberty to add JAXB 4.0 support.
Are you willing to host the new release, or shall I take it back under my coordinates?

The tricky thing is to compile all the base components with Java 8 and only jaxb40-maven-plugin with Java 11.

I tested it locally against some (complex) projects and it works for me

### CODE REVIEW

**Comment by phax** [comment]
And I needed to change the dependency for the XML Catalog Resolver, due to Java 11 incompatibility. The new dependency is
```xml
      <groupId>org.netbeans.external</groupId>
      <artifactId>resolver-1.2</artifactId>
      <version>RELEASE160</version>
```

**Comment by adamretter** [comment]
@phax Thanks for this, it looks very interesting. I have spent some hours today fixing the tests, CI, and bringing dependencies up to date. Would you be able to merge/rebase, so that I can get the benefit of the tests and CI for your PR.

I also note that your PR appears to include a lot of code style reformatting - I would rather avoid those changes, as it makes it hard to pick out the real changes that you intended.

Regards the `XML Catalog Resolver` I wonder if a more modern option might be - https://xmlresolver.org/ - if it is compatible?

**Comment by phax** [comment]
Cool Thanks @adamretter 
I merged the changes back and it looks good on my side as well.

There's one minor thing in the GitLab actions YAML: Java 8 is no longer a valid target, because it cannot be used to build plugin-4.0. Maybe we can use Maven profiles for that? I will git it a quick try

I tried with xmlresolver.org but I found out, that they only support Catalog XML files, but not the old OASIS test based catalog files - so I needed to use another dependency.

**Comment by adamretter** [comment]
@phax thanks I will try and take a look in the next few days and bring this up to date to pass CI again

**Comment by phax** [comment]
So I think the tests are fixed - now it just needs your approval :)

**Comment by phax** [comment]
@adamretter do you have any plan forward on this one? Otherwise I would need to build my own release and I want to avoid that. Sorry for pushing you :-/

**Comment by cemo** [comment]
Hi @adamretter, we have a few projects are waiting this project.  We will be really grateful if you merge and release it since It will trigger some chaining releases :)

**Comment by phax** [comment]
@adamretter  Sorry, I need to close this PR for now. I did an "inofficial" release with the "com.helger" group and discovered some errors deep down in CatalogResolver which lead me to the conclusion to integrate the used Resolver into the plugin (based on Apache xml-resolver:xml-resolver:1.2). So this PR is too far off from what I am currently using - sorry

**Pull request closed without merging**
